name: my-website
output_dir: .
navbar:
  title: Deep Learning
  left:
  - text: Home
    href: index.html
  - text: Week 1
    href: week_01.html
  - text: Week 2
    href: week_02.html
output:
  tufte::tufte_html:
    self_contained: yes

